version: "3"   #指定compose文件版本
services:      #指定当前脚本要运行的容器内容
 lagou-nginx:   #创建一个nginx应用
    image: nginx:1.19.3-alpine   #指定镜像版本
    container_name: lagou-nginx  #指定容器名称
    ports:  #指定端口映射
    - 80:80
    - 808:80
    volumes:  #指定数据卷挂载
    - d://nginx_data/nginx:/etc/nginx
    restart: always  #指定启动策略
 lagou-tomcat1:
    image: tomcat:9.0.20-jre8-alpine
    container_name: lagou-tomcat1
    ports:  
    - 8081:8080
    volumes:
    - d://mysql_data/tomcat1/webapps:/usr/local/tomcat/webapps
    restart: always  
    depends_on: 
      - lagou-nginx  
 lagou-tomcat2:
    image: tomcat:9.0.20-jre8-alpine
    container_name: lagou-tomcat2
    ports:  
    - 8082:8080
    volumes:
    - d://mysql_data/tomcat2/webapps:/usr/local/tomcat/webapps
    restart: always  
    depends_on: 
      - lagou-nginx  

